data:
  query_data:
    beginTime: null
    duration: null
    num: '1'
    space_category[category_id]: '591'
    space_category[content_id]: '3'
seat_list: []
session:
  headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101
      Firefox/101.0
  params:
    LAB_JSON: '1'
  trust_env: false
  urls:
    book_seat: https://hdu.huitu.zhishulib.com/Seat/Index/bookSeats
    login: https://hdu.huitu.zhishulib.com/User/Index/login
    query_seats: https://hdu.huitu.zhishulib.com/Seat/Index/searchSeats
  verify: false
settings:
  incident: 3
  max_try_times: 50
user_info:
  login_name: null
  org_id: '104'
  password: null
